spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/jboot_chu?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: salem
    password: salem

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  
  

logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.salem: debug
    